feat(ui-home): Initial push for sw360-frontend-nextjs home page
eclipse-sw360/sw360-frontend pull request #17
Opened 2023-04-26 07:10 UTC by amritkv17

2023-04-26 10:49 UTC, heliocastro commented
/me HAPPY

2023-04-26 10:51 UTC, heliocastro requested changes
Why commitlint was removed ???

2023-04-26 10:52 UTC, ag4ums commented
@amritkv17, Please add copyright and license headers in all the new/modified files.

2023-04-26 11:31 UTC, heliocastro commented
@amritkv17 Do the copyrights in this way:

```Copyright (C) 2023 SW360 Project Authors (see <https://github.com/eclipse-sw360/sw360/NOTICE>)```

And inside NOTICE file add your company data / personal data

2023-04-26 14:46 UTC, heliocastro requested changes
@amritkv17 
Again:
1 - Why commit lint was removed ?
2 - Why now prettier comfig was removed
3 - Why we have a yarn.lock, there's never an agreement about to start use Yarn. ONLY npm should be used
4 - No PNG files, only svg.

2023-04-26 15:02 UTC, heliocastro requested changes
Please address all entries

2023-04-27 06:30 UTC, amritkv17 commented on src/components/SearchVendorsModal/index.tsx
Resolved this issue. :)

2023-04-27 06:30 UTC, amritkv17 commented on src/components/footer.tsx
> - */
I am really sorry for this mistake. Resolved this issue. :)

2023-04-27 06:31 UTC, amritkv17 commented on src/utils/table-builder/buildTables.tsx
Resolved this issue. :)

2023-04-27 06:32 UTC, amritkv17 commented on .eslintrc.json
Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:32 UTC, amritkv17 commented on .prettierrc.js
Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:33 UTC, amritkv17 commented on commitlint.config.js
Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:35 UTC, amritkv17 commented on src/utils/pagination/Pagination.tsx
Resolved this issue. :)

2023-04-27 06:35 UTC, amritkv17 commented on src/utils/table-builder/buildTable.module.css
Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:35 UTC, amritkv17 commented on src/utils/env.ts
Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:36 UTC, amritkv17 commented on src/utils/pagination/pagination.module.css
Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:38 UTC, amritkv17 commented on src/pages/api/auth/[...nextauth].ts
Actually, few endpoints are yet to be developed. And due to this, we haven't yet integrated the authentication code written by Toshiba colleagues into our code. That's why it shows removed.

2023-04-27 06:39 UTC, amritkv17 commented on src/styles/auth.css
Actually, few endpoints are yet to be developed. And due to this, we haven't yet integrated the authentication code written by Toshiba colleagues into our code. That's why it shows removed.

2023-04-27 06:39 UTC, amritkv17 commented on public/images/logo-edited.svg
I am working on it. :)

2023-04-27 06:39 UTC, amritkv17 commented on public/images/profile.png
I am working on it. :)

2023-04-27 06:40 UTC, amritkv17 commented on src/components/SelectCountry.tsx
Thanks for the suggestion. I am working on it. :)

2023-04-27 06:40 UTC, amritkv17 commented
> @amritkv17 Do the copyrights in this way:
> 
> `Copyright (C) 2023 SW360 Project Authors (see <https://github.com/eclipse-sw360/sw360/NOTICE>)`
> 
> And inside NOTICE file add your company data / personal data

Resolved this issue. :)

2023-04-27 06:42 UTC, amritkv17 commented
> @amritkv17, Please add copyright and license headers in all the new/modified files.

Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:43 UTC, amritkv17 commented
> Why commitlint was removed ???

Thanks for pointing out, it was by mistake. Resolved this issue. :)

2023-04-27 06:45 UTC, amritkv17 commented
> @amritkv17 Again: 1 - Why commit lint was removed ? 2 - Why now prettier comfig was removed 3 - Why we have a yarn.lock, there's never an agreement about to start use Yarn. ONLY npm should be used 4 - No PNG files, only svg.

Point 1 & 2:  Thanks for pointing out, it was by mistake. Resolved this issue. :)
Point 3 & 4:  I am working on it. :)

2023-04-29 08:18 UTC, heliocastro requested changes
Take a look on this:
![image](https://user-images.githubusercontent.com/418176/235292468-5cc36a6c-aefc-44bc-9c51-f4d6f6738cd5.png)

So, PLEASE add back the Toshiba next-auth work, and add a flag option if you do not want automatic auth in the test environment, but NEVER remove work done.

Toshiba made an excellent job using the right approach from the beginning, let's not screw this up, ok ?

2023-04-29 08:21 UTC, heliocastro commented on package.json
4 - Did you noticed that you removed coer packages like country-flag icons and next-auth ?

2023-05-05 10:11 UTC, heliocastro requested changes
Why do you removed the empty line on end of all files ?
The large majority of linters complain about files without extra empty line.
Maybe you should config your editor to change this behaviour.

2023-05-05 10:11 UTC, heliocastro commented on src/components/SelectCountry.tsx
Don't do that **again**
Use something stablished:
https://www.npmjs.com/package/country-list

2023-05-05 10:11 UTC, heliocastro commented on src/pages/_document.tsx
> +
Don't do this way.
Use this or similar class:
https://www.npmjs.com/package/react-bootstrap-icons

2023-05-05 10:11 UTC, heliocastro commented on src/services/home.service.ts
> +        opts.headers['Access-Control-Allow-Origin'] = '*';
**ALERT** Token in code !!!

2023-05-08 17:57 UTC, amritkv17 commented on src/services/home.service.ts
> +        opts.headers['Access-Control-Allow-Origin'] = '*';
Addressed this issue ! :)

2023-05-08 17:57 UTC, amritkv17 commented on src/components/SearchVendorsModal/index.tsx
Addressed this issue ! :)

2023-05-10 01:03 UTC, heliocastro submitted a review, later dismissed
Please rebase and then good to go

2023-05-12 18:02 UTC, heliocastro approved these changes
Let's start the grid.js move :-)

2023-05-12 18:05 UTC, heliocastro commented
@amritkv17 Please check the validation of commits.
PR is good, no need to change the code, just fix the header

2023-05-12 18:09 UTC, amritkv17 commented
> @amritkv17 Please check the validation of commits. PR is good, no need to change the code, just fix the header

@heliocastro Thanks ! I am on it. :)

And once this PR is ready, I will incorporate `gridjs` too.

2023-05-12 18:17 UTC, heliocastro commented
@amritkv17 You can run this locally to check before commit from inside the top source dir:
```bash
docker run -it --rm -v $(pwd):/github/workspace ghcr.io/apache/skywalking-eyes/license-eye header
```

2023-05-12 18:44 UTC, amritkv17 commented
> @amritkv17 Please check the validation of commits. PR is good, no need to change the code, just fix the header

@heliocastro Is it necessary to put licensing header in the `.json` files also ?

2023-05-12 18:56 UTC, heliocastro commented
If the json file accepts, yes.
If the parser complains, add an exception on the .license file.

But exception is exception, always add a license in any file

2023-05-12 21:05 UTC, heliocastro approved these changes
Finally good to go

2023-05-12 21:05 UTC, heliocastro commented
@amritkv17 Is there any commit missing signing ?

2023-05-12 21:56 UTC, KoukiHama approved these changes

2023-05-13 07:24 UTC, ag4ums commented
@amritkv17, seems commit history is messed up, please created a new branch from the main and merge the code there.
and close this PR once you create the new one.

2023-05-13 10:44 UTC, amritkv17 commented
Closing this PR. New Pr is here(https://github.com/eclipse-sw360/sw360-frontend/pull/29)

2023-05-13 10:44 UTC, closed without merging