Project detail ECC Page and minor bug fixes
eclipse-sw360/sw360-frontend pull request #170
Opened 2023-11-16 12:51 UTC by deo002

2023-11-16 13:15 UTC, heliocastro requested changes
Some small requests inline.
Maybe rename Ecc to ECC in all places ?

2023-11-17 04:19 UTC, hoangnt2 commented on src/app/[locale]/projects/components/Projects.tsx
> +                    {status === 'authenticated' ? (
@heliocastro, useSession take a few seconds to retrieve authentication status so we need to check this where useSession is used

2023-11-17 06:41 UTC, heliocastro commented on src/app/[locale]/projects/components/Projects.tsx
> +                    {status === 'authenticated' ? (
Maybe we're looking wrong and we should protect the routes in different way.
I will approve this one and we try to do something similar like this:
https://www.freecodecamp.org/news/how-to-setup-authentication-and-protected-route-in-next-js-13-with-next-auth-js/

2023-11-17 06:42 UTC, heliocastro approved these changes
Approved with a TODO:
Revise route protection in system

2023-11-17 06:42 UTC, merged

2023-11-17 06:57 UTC, hoangnt2 commented on src/app/[locale]/projects/components/Projects.tsx
> +                    {status === 'authenticated' ? (
@heliocastro, actually we have route protection in our application (middleware) and it works fine.
What I mean is, when we use the useSession() hook, the state is always **unauthenticated** at the initial time. After a few seconds, the state will be updated (real state) and the component will be re-render.
That's why I get session on server side and send it to client component as a prop.