feat(project_attachment_usages): Add table for project attachments
eclipse-sw360/sw360-frontend pull request #214
Opened 2024-02-12 11:10 UTC by deo002

2024-02-12 11:51 UTC, heliocastro requested changes
Please don't reformat entire en.json.
Can you redo the commit only with effective change ?

2024-02-13 05:33 UTC, deo002 commented
> Please don't reformat entire en.json. Can you redo the commit only with effective change ?

It is reformatting on it's own when I do a commit. I tried a few things, but none of them are working. Can you help me with this?

2024-02-13 07:56 UTC, heliocastro approved these changes

2024-02-13 07:56 UTC, merged

2024-02-13 07:58 UTC, heliocastro commented
@deo002 Ok, if the linter is formatting on this way is fine. I needed deactivate prettier-quick due incompatibility of current codebase, so let's not fight over it.