feat(project_deatil): Added feature to generate source code bundle
eclipse-sw360/sw360-frontend pull request #235
Opened 2024-03-19 06:35 UTC by amritkv

feat(project_deatil): Added feature to generate source code bundle at project detail page

Note :  Yet to incorporate with rest-api (as rest-api is under development)

2024-03-19 06:46 UTC, heliocastro requested changes
Code is good, but your editor or prettier config is removing blank last line on the sources.
Please add an extra empty line on end of all this codes and/or adjust your editor.

2024-03-19 06:49 UTC, amritkv commented
> Code is good, but your editor or prettier config is removing blank last line on the sources. Please add an extra empty line on end of all this codes and/or adjust your editor.

Sure @heliocastro ! I will do that. 👍

2024-03-19 10:38 UTC, heliocastro requested changes
Blank lines

2024-03-19 10:38 UTC, heliocastro commented on src/styles/globals.css
> -}
Removing blank line

2024-03-19 10:38 UTC, heliocastro commented on src/app/[locale]/projects/generateSourceCode/[id]/page.tsx
No blank line in the end of code

2024-03-19 10:38 UTC, heliocastro commented on src/app/[locale]/projects/generateSourceCode/[id]/components/GenerateSourceCodeBundle.tsx
No blank line at end of code

2024-03-22 06:17 UTC, heliocastro requested changes
Please fix the log message

2024-03-22 09:28 UTC, heliocastro approved these changes
Please fix the editor next time

2024-03-22 09:28 UTC, heliocastro commented on src/styles/globals.css
> -}
Still removing a blank line at the end. This time let it pass.

2024-03-22 09:29 UTC, heliocastro commented
@amritkv Still WIP ?

2024-03-22 10:25 UTC, amritkv commented
> Please fix the editor next time

Hey @heliocastro ! In my case, my `.prettierrc.json` file looks exactly the same as it is in main.
I'm not sure, where the prob is. Can you please help me here.

![image](https://github.com/eclipse-sw360/sw360-frontend/assets/52911458/765eeb17-bfc4-4370-89ad-a5611347f902)

2024-03-22 10:39 UTC, amritkv commented
> @amritkv Still WIP ?

I'm not sure whether we can merge it without API integration. If we can, then I can make it ready to merge.

2024-03-22 10:45 UTC, heliocastro commented
@amritkv That's why i mentioned your editor. Prettier don't have an configuration for end of line, this comes strictly from the editor.
For example, in Visual Studio Code you need to add this in configuration: files.insertFinalNewline = True
In IDEA IntelliJ is: Settings → Editor → General → Ensure line feed at file end on Save

2024-03-22 10:52 UTC, amritkv commented
> iles.insertFinalNewline = True

@heliocastro , The config of my vs code editor is also the same as earlier.
May be I have to update/do a fresh configuration of my editor. 

![image](https://github.com/eclipse-sw360/sw360-frontend/assets/52911458/adbcf111-3e82-4047-8a81-25fe28f7011d)

2024-04-05 09:38 UTC, merged