feat(packages): Add package details page
eclipse-sw360/sw360-frontend pull request #297
Opened 2024-07-29 09:44 UTC by deo002

### Url
http://localhost:3000/packages/detail/{id}

### Screenshots
![image](https://github.com/user-attachments/assets/3d07632d-88dc-4763-b7ee-1881e786713e)

2024-07-29 13:29 UTC, heliocastro requested changes
Remove custom css and use global on

2024-07-29 13:29 UTC, heliocastro commented on src/app/[locale]/packages/detail/[id]/detail.module.css
Please do not reinvent the wheel.
Why add **again** css for components that are global.
Please reuse the global css.

2024-07-30 11:11 UTC, deo002 commented
The css was used locally at many places. Making it global required changes in a lot of places which made the PR big. Should I add the second commit in another PR? @heliocastro

2024-08-05 09:07 UTC, heliocastro commented
> The css was used locally at many places. Making it global required changes in a lot of places which made the PR big. Should I add the second commit in another PR? @heliocastro

Yes, you should.
The fact is using in a lot places is enough information that should be global. Local solution just hurt maintenance, quality of the code, and future possible changes

2024-08-06 10:48 UTC, deo002 commented
> > The css was used locally at many places. Making it global required changes in a lot of places which made the PR big. Should I add the second commit in another PR? @heliocastro
> 
> Yes, you should. The fact is using in a lot places is enough information that should be global. Local solution just hurt maintenance, quality of the code, and future possible changes

Ok, I'll add the follow up PR after rebasing once this one is merged.

2024-08-13 05:29 UTC, heliocastro approved these changes
I will merge this one. 
@deo002 Please fix this. I will remember you from now one every time you make a new PR, until this is fixed.
@hoangnt2 We should do a cleanup on CSS, and after that forbid any of this things again.

2024-08-13 05:30 UTC, heliocastro commented
@deo002 You need rebase this commit

2024-08-19 05:34 UTC, deo002 commented
> I will merge this one. @deo002 Please fix this. I will remember you from now one every time you make a new PR, until this is fixed. @hoangnt2 We should do a cleanup on CSS, and after that forbid any of this things again.

I'll push a fix right after this is merged

2024-08-19 12:42 UTC, heliocastro approved these changes
This CSS need to move to global...

2024-08-19 12:43 UTC, merged