fix(Projects): fix bugs in Project list
eclipse-sw360/sw360-frontend pull request #360
Opened 2024-11-29 10:28 UTC by duonglq-tsdv

# Pull Request Description

### What does this PR do?
1. [Project list] Fixes the error of unable to delete a project.
2. [Project list] Fixes the error of unable to create clearing request.
3. [Update Project] Fixes the error of no data in the "Project Owner" field.
4. [Update Project] Fixes the error of no "You are editing the original project" when clicking the edit icon from Project list.

---

### Pre-condition:
- The user has logged in and there are at least one project created on Project list

---

### How to Test?

#### 1. Fixes the error of unable to delete a project

**Procedure:**
- Procedure 1: On the project list page, click the delete button below Action column to delete a project.
- Procedure 2: On the update project page, click the "Delete Project" button.

**Expected:**
+ "Delete Project" dialog is displayed with message "Do you really want to delete the project?"
+ Delete button is enable
+ Delete the project successfully when clicking on "Delete Project" button
---

#### 2. Fixes the error of unable to create clearing request

**Procedure:**
- Click on "Create Clearing Request" button under Actions column

**Expected:**
+ Clearing Request dialog is opened, and allow create clearing request.
---

#### 3. Fixes the error of no data in the "Project Owner" field

**Procedure:**
- At view project mode, there is data in the "Project Owner" field.
- Click on "Edit Projects" button

**Expected:**
+ Data in the "Project Owner" field matches the data at view page

#### 4. Fixes the error of no "Success: You are editing the original document." when clicking the edit icon from Project list

**Procedure:**
- Login as an user, then create a project.
- In the project list page, click on edit button under "Action" column.

**Expected:**
+ The message  "Success: You are editing the original document." is displayed.

2024-12-02 07:12 UTC, hoangnt2 requested changes

2024-12-02 07:12 UTC, hoangnt2 commented on src/app/[locale]/projects/edit/[id]/components/EditProject.tsx
> +                    setProjectOwner({ 'Project owner':
project owner must have format
`{email : full name}`
for example:
{ 'admin@sw360.org': 'Test Admin'}

2024-12-04 07:08 UTC, heliocastro approved these changes
Looks good

2024-12-04 10:09 UTC, hoangnt2 approved these changes
Look good to me

2024-12-04 12:12 UTC, merged