feat(release): Add release - Get data Additional Roles, External ids, Additional Data, Release Repository
eclipse-sw360/sw360-frontend pull request #97
Opened 2023-08-28 10:20 UTC by tuannn2

Create Release

- Get data Additional Roles, External ids, Additional Data, Release Repository

![GetData](https://github.com/eclipse-sw360/sw360-frontend/assets/94596393/c831e786-bc41-4dff-b421-613e28c0573e)

2023-08-28 12:09 UTC, heliocastro requested changes
Small typo on component

2023-08-28 12:09 UTC, heliocastro commented on src/components/ReleaseSummary/ReleaseSummary.tsx
> +                            <ModeratorsDiaglog
Typo here.

2023-08-29 02:03 UTC, hoangnt2 commented
look good

2023-08-30 06:47 UTC, hoangnt2 approved these changes

2023-08-30 14:43 UTC, merged