feat(Release): Get Data Other License, Linked Releases
eclipse-sw360/sw360-frontend pull request #99
Opened 2023-08-31 03:20 UTC by tuannn2

Create Release

- Get Data of Other License
- Get Data Linked Releases

![LinkedRelease](https://github.com/eclipse-sw360/sw360-frontend/assets/94596393/e4aa29ea-c38a-46a3-8868-cd4a4cd9680c)

2023-08-31 11:47 UTC, heliocastro requested changes
Pleas fix the typo and will be ok

2023-08-31 11:47 UTC, heliocastro commented on src/components/ReleaseSummary/ReleaseSummary.tsx
> +import OtherLicensesDiaglog from '../sw360/SearchOtherLicenses/OtherLicensesDialog'
Typo

2023-08-31 11:47 UTC, heliocastro commented on src/components/ReleaseSummary/ReleaseSummary.tsx
> +                            <OtherLicensesDiaglog
Typo ( Dialog x Diaglog )

2023-08-31 11:47 UTC, heliocastro commented on src/components/sw360/SearchOtherLicenses/OtherLicensesDialog.tsx
> +const OtherLicensesDiaglog = ({ show, setShow, session, selectLicenses }: Props) => {
Type again

2023-09-05 01:56 UTC, tuannn2 commented on src/components/sw360/SearchOtherLicenses/OtherLicensesDialog.tsx
> +const OtherLicensesDiaglog = ({ show, setShow, session, selectLicenses }: Props) => {
fixed.

2023-09-05 06:33 UTC, heliocastro approved these changes

2023-09-05 06:33 UTC, merged